seed: 42
device: cpu

network:
  n_agents: 10
  models:
    [
      vit_base_patch16_224,
      vit_base_patch32_clip,
      vit_small_patch16_224,
      vit_small_patch32_224,
      vit_tiny_patch16_224,
    ]
  datasets: [cifar10, cifar10, cifar10, cifar10, cifar10]
  node_dims: [192]
  p_edges: 0.4
  path: /results/learned_sheaf/

algorithm:
  n_iter: 40
  alpha: 0.1
  lambda_: 0.1
  tau_a: 0.0001
  tau_r: 0.0001
  verbose: true
  n_edges: 8

evaluation:
  dataset: cifar10
  batch_size: 128
