defaults:
  - _self_

seed: 200 # [27, 42, 100, 123, 144, 200]

datamodule:
  dataset: cifar10
  rx_enc: vit_small_patch32_384

classifier:
  hidden_dim: 10
  lr: 1e-2
    
trainer:
  num_sanity_val_steps: 2
  max_epochs: 100
  deterministic: True
  log_every_n_steps: 10
    
wandb:
  project: semantic_network_formation_sheaves__classifier

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      datamodule.rx_enc: efficientvit_b2, efficientvit_m4, efficientvit_m5, lcnet_075, levit_128, levit_128s, levit_192, levit_conv_128, levit_conv_128s, levit_conv_192, volo_d1_224, volo_d1_384, xcit_small_12_p16_224, xcit_small_12_p16_384, cait_s24_224, cait_s24_384, cait_s36_384 
